version: '3'

services:
  db:
    image: postgres
  web:
    environment:
      - PORT=3000
      - PG_HOST=db
      - HOST=0.0.0.0
    build: .
    command: ["./wait-for-postgres.sh", "db", "some-paste-exe"]
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
