name:                some-paste
version:             0.1.0.4
github:              "nitros12/some-paste"
license:             MIT
author:              "Ben Simms"
maintainer:          "ben@bensimms.moe"
copyright:           "2018 Ben Simms"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.comadme>

dependencies:
- base       >= 4.7  && < 5
- skylighting >= 0.4
- postgresql-simple >= 0.5
- opaleye >= 0.5
- bytestring >= 0.10
- product-profunctors >= 0.8
- blaze-html >= 0.9
- time >= 1.6
- text-format >= 0.3
- clay >= 0.12
- containers >= 0.5
- mtl >= 2.2
- resource-pool >= 0.2
- ekg >= 0.4
- envy >= 1.3
- scotty >= 0.11
- ekg >= 0.4
- wai-extra >= 3.0
- resource-pool >= 0.2
- data-default-class >= 0.1
- directory >= 1.3
- wai-middleware-throttle >= 0.2
- text
- xxhash
- http-types
- warp
- wai
- hspec
- hspec-wai
- basic-prelude

library:
  source-dirs: src

executables:
  some-paste-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - some-paste

tests:
  some-paste-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - some-paste
