flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- skylighting-0.3.3.1
- xxhash-0.0.2
resolver: lts-9.3
docker:
  enable: true
image:
  container:
    base: fpco/stack-build
    name: some-paste
